version: '3.8'
services:
 bits-backend:
   container_name: bits-backend
   restart: always
   image: bits-backend:1
   depends_on:
     - bits-redis
   ports:
     - '8080:8080'
   environment:
     - NODE_ENV=development
     - PORT=8080
     - MONGO_URL=mongodb+srv://anhminhbo:Anhminh1234@bits-local.gvnypfl.mongodb.net/?retryWrites=true&w=majority
     - REDIS_HOST=bits-redis
     - REDIS_PORT=6379
     - SESSION_SECRET=randomsessionsecret

 bits-frontend:
   container_name: bits-frontend
   restart: always
   image: bits-frontend:1
   depends_on:
     - bits-redis
     - bits-backend
   ports:
     - '3000:80'
   environment:
     - NODE_ENV=development
     - BACKEND_URL=http://localhost:8080
     - WDS_SOCKET_PORT=0
     - API_KEY=AIzaSyAmltDENBZXKAf_pBzRbXZp9mISeRGl52M

 bits-redis:
    container_name: bits-redis
    restart: always
    image: redis:6.2-alpine
    ports:
     - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning