version: '3.8'
services:
#  bits-backend:
#    container_name: bits-backend
#    restart: always
#    image: anhminhbo/bits-backend:22
#    depends_on:
#     - bits-redis
#    ports:
#    - '8080:8080'
#    environment:
#      - NODE_ENV=production
#      - PORT=8080
#      - MONGO_URL=mongodb+srv://anhminhbo:Anhminh1234@bits-local.gvnypfl.mongodb.net/?retryWrites=true&w=majority
#      - REDIS_HOST=bits-redis
#      - REDIS_USERNAME=default
#      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#      - REDIS_PORT=6379
#      - SESSION_SECRET=randomsessionsecret
    
  bits-redis:
    container_name: bits-redis
    restart: always
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning


#  bits-frontend:
#    container_name: bits-frontend
#    restart: always
#    image: anhminhbo/bits-frontend:[[FRONTEND_TAG]]
#    ports:
#    - '3000:3000'
#    environment:
#      - REACT_APP_BACKEND_URL=http://localhost:8080
#      - WDS_SOCKET_PORT=0